{% set data = load_setup_py_data() %}

package:
  name: simple_h5py
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - h5py
    - numpy

  run:
    - python
    - h5py
    - numpy

test:
  imports:
    - simple_h5py

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
